tools:
    shell:
        allow:
            - ls *
            - wc *
            - git diff *
            - echo *
            - python3 *
            - head *
            - tail *
            - sleep 15
            - grep *
            - ps aux
            - cat *
            - sort
            - git status *
            - git log *
            - git checkout d39ba1e *
            - git stash *
            - git add *
            - git commit *
            - git checkout *
            - python *
            - sleep 20
            - ./gradlew compileJava
            - sleep 30
            - sleep 10
            - curl *
            - ./gradlew clean *
            - sleep 35
            - pkill *
            - awk *
            - xargs *
            - find *
            - sed *
            - diff *
            - sleep 5
            - "true"
            - cut *
            - uniq *
            - ./gradlew test
            - cd *
            - mv *
            - '[ *'
            - ./gradlew test *
            - sort *
            - sleep 3
            - ./gradlew bootRun *
            - ./gradlew *
            - unzip *
            - strings
            - jar tf *
            - git show *
